stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lafamiliajo/final:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
  when:
    event:
      include:
      - tag
