stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lafamiliajo/final:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
