stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lafamiliajo/final:latest
      pushRemote: true
      registry: index.docker.io
