stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lafamiliajo/final:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
  when:
    event: {}
