apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: u-rgqwdna44s
    field.cattle.io/publicEndpoints: '[{"addresses":["18.185.16.225"],"port":443,"protocol":"HTTPS","serviceName":"p-66nfk-pipeline:ingress-42275434e1f66e77ad40f937a1304a59","ingressName":"p-66nfk-pipeline:web","hostname":"shop.test.lafamilia-jo.com","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-p-66nfk-pipeline-web
  name: web
  selfLink: /apis/apps/v1beta2/namespaces/p-66nfk-pipeline/deployments/web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-p-66nfk-pipeline-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-12-20T13:21:46Z
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"web","kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-p-66nfk-pipeline-web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: magento-config-map
            optional: false
        image: ${CICD_IMAGE}:${CICD_GIT_TAG}
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dh-lafamilia-jo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

